[package]
name = "meowed-away"
version = "0.1.0"
edition = "2024"
authors = ["Chaya <chaya@example.com>"]
description = "Don't Get Meowed Away"
license = "MIT/Apache-2.0"
repository = "https://github.com/coplat/meowed-away"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
